# Generated by Django 5.2.6 on 2025-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
